# wrangler.toml

# 核心配置
name = "moments-workers"
main = "./src/worker/index.js"
compatibility_date = "2025-04-01"

# 启用 Node.js 兼容性
compatibility_flags = ["nodejs_compat"]

# 启用 Observability（日志、指标等）
[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = ""
database_id = ""
preview_database_id = ""

[vars]
TG_BOT_TOKEN = ""
TG_CHAT_ID = ""
DOMAIN = ""

kv_namespaces = [
  { binding = "IMAGE", id = "",preview_id=''}
]

# 静态资源托管配置
[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]